services:
  - type: web
    name: n8n
    env: docker
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /healthz

    envVars:
      - key: DB_TYPE
        value: postgresdb

      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8nDB
          property: host

      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8nDB
          property: database

      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8nDB
          property: port

      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8nDB
          property: user

      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8nDB
          property: password

      - key: DB_POSTGRESDB_SSL_ENABLED
        value: "true"

      - key: PORT
        value: "5678"

      - key: N8N_PORT
        value: "5678"

      - key: N8N_LOG_LEVEL
        value: info

      - key: GENERIC_TIMEZONE
        value: Europe/Paris

      - key: TZ
        value: Europe/Paris

      - key: N8N_DEFAULT_LOCALE
        value: fr

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      - key: N8N_UNVERIFIED_PACKAGES_ENABLED
        value: "true"

      - key: N8N_RUNNERS_TASK_TIMEOUT
        value: "300"

      - key: N8N_COMPRESSION_NODE_MAX_DECOMPRESSED_SIZE_BYTES
        value: "2147483648"

      - key: N8N_COMPRESSION_NODE_MAX_ZIP_ENTRIES
        value: "5000"

databases:
  - name: n8nDB
    plan: free